from .accountant_routes import *
from .director_routes import *
from .expense_routes import *
from .fees_routes import *
from .invoice_routes import *
from .main_routes import *
from .payroll_routes import *
from .school_fee_routes import *
from .secretary_routes import *
from .students_routes import *
